# .github/workflows/docker-build.yml
name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v0.3.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Needed for GHCR
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from tag
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push to GHCR
        run: |
          docker build -t ghcr.io/kitquietdev/rmeta:${VERSION} .
          docker tag ghcr.io/kitquietdev/rmeta:${VERSION} ghcr.io/kitquietdev/rmeta:latest
          docker push ghcr.io/kitquietdev/rmeta:${VERSION}
          docker push ghcr.io/kitquietdev/rmeta:latest

      - name: Build and push to Docker Hub
        run: |
          docker build -t kitquietdev/rmeta:${VERSION} .
          docker tag kitquietdev/rmeta:${VERSION} kitquietdev/rmeta:latest
          docker push kitquietdev/rmeta:${VERSION}
          docker push kitquietdev/rmeta:latest
