name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ secrets.GHCR_USERNAME }}/rmeta:latest
            ghcr.io/${{ secrets.GHCR_USERNAME }}/rmeta:${{ github.ref_name }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip uninstall PyPDF2
          pip install pypdf>=3.9.0
          echo "import PyPDF2" > test_import.py
          python test_import.py
#          